### ISSUE TITLE
Value of `fname` in `2_3-Pathology Diagnosis Modeling.py` (and also other files)

### ISSUE THREAD

**Issue by khoaguin** [lrsoenksen/HAIM#1]
I am studying the file `2_3-Pathology Diagnosis Modeling.py`. It has a variable `fname` which is supposed to hold the filename of the embedding file. I am wondering is it the file `Extracted_HAIM_Embeddings/cxr_ic_fusion_1103.csv` file from https://physionet.org/content/haim-multimodal/1.0.1/?

**Comment by lrsoenksen** [comment]
It is! Thanks for the question!
