### ISSUE TITLE
Definitions of records

### ISSUE THREAD

**Issue by ArbelHaiman** [lrsoenksen/HAIM#10]
Hi,

I'm trying to create the dataset you created for the research. At MIMIC-CXR there are only the subject_id and study_id identifiers, but in MIMIC-IV, there are the subject_id, hadm_id adn stay_id. What is the correct way to link images from MIMIC-CXR to data from MIMIC-IV? I understand from your article that records are defined by {subject_id, hadm_id, stay_id}, but I don't understand how should I select the matched images to each records?
Perhaps you can describe in detail what a single record is composed of, in terms of data from all sources?
Thank you

**Comment by AliRasekh** [comment]
Hi, 

This is my question as well.

**Comment by lrsoenksen** [comment]
We show how we assigned HAIM_IDs in the '1_1-Create Pickle Files.py file'
[1_1-Create Pickle Files.py](https://github.com/lrsoenksen/HAIM/blob/main/1_1-Create%20Pickle%20Files.py)

SEE THE FOLLOWING LINE:

### Get Unique Subject/HospAdmission/Stay Combinations with Chest Xrays
df_haim_ids = df_ids[df_ids['subject_id'].isin(df_cxr_ids['subject_id'].unique())]
