### ISSUE TITLE
Patient vs Admission level aggregation

### ISSUE THREAD

**Issue by jf-11** [lrsoenksen/HAIM#12]
I have looked at the code that is used to generate the multimodal dataset. From my understanding all data except the CXR scans are aggregated on the level of unique admissions (based on `hadm_id`) but the CXR scans are aggregated on a patient level (based on `subject_id`), meaning that CXR scans belong to a patient and its multiple admissions but are not attributed to a specific admission.

Can you confirm if I am right with my assumption?
Thank you!

**Comment by lrsoenksen** [comment]
Yes, you are correct. Through this structure one can opt to access all admissions for a single patient to try doing predictions considering all past data of an individual, but also it can be filtered to only consider the data from most immediate admission.
