### ISSUE TITLE
Tensorflow can removed from the requirements

### ISSUE THREAD

**Issue by FrozenWolf-Cyber** [lrsoenksen/HAIM#16]
I don't see any use of the TensorFlow library; I suppose it can be removed from requirements.txt, yaml and in `MIMIC_IV_HAIM_API.py `?

**Comment by lrsoenksen** [comment]
I believe you can, as I think this was a remanent of a few Deep neural network experiments we did.  That being said there are parts of the code for embedding generation that depend on a few pre-trained medical imaging vision models, some of which may require tensorflow or pytorch to work, so probably you need to verify what sections of the code you are interested on using.
