### ISSUE TITLE
Files does't match with mimic-iv 3.0 and mimic-cxr-jpg 2.0

### ISSUE THREAD

**Issue by JuneHou** [lrsoenksen/HAIM#17]
Hi,

Thank you for open source the code for this research.

When I try to generate the dataset, I find the file doesn't match the newest mimic-iv. In addition, I cannot find "mimic-cxr-jpg/2.0.0/mimic-cxr-2.0.0-jpeg-txt.csv" in mimic-cxr-jpg v2.0.0, which should be the same one used in the project, and I cannot find any update mentioned this jpeg-txt.csv.

Is this file downloaded from any specific version of mimic-iv or generated?

Best,
Jun

**Comment by lrsoenksen** [comment]
This work was generated with the most recent MIMIC dataset we had availability to access at the time of publication. The exact version is all described in the paper (https://www.nature.com/articles/s41746-022-00689-4). It indeed may be the case that by the time you are trying to replicate this, the files may not match because the Physionet team does update their data versioning often. This is precisely why we added all the code we used to create the aggregated databases, etc. To allow for others to potentially use those to generate their own aggregated databases, embeddings and models. However, we will not directly support these adaptations as we do not currently have the bandwith to attend to this. We are actually working in much more scalable and future proofs to bring multimodality to clinical care.

**Comment by JuneHou** [comment]
> This work was generated with the most recent MIMIC dataset we had availability to access at the time of publication. The exact version is all described in the paper (https://www.nature.com/articles/s41746-022-00689-4). It indeed may be the case that by the time you are trying to replicate this, the files may not match because the Physionet team does update their data versioning often. This is precisely why we added all the code we used to create the aggregated databases, etc. To allow for others to potentially use those to generate their own aggregated databases, embeddings and models. However, we will not directly support these adaptations as we do not currently have the bandwith to attend to this. We are actually working in much more scalable and future proofs to bring multimodality to clinical care.

Thank you for the reply. I have created the aggregated database using your detailed code. Appreciate you making all the code open-source.

However, in the notebook `1_Generate HAIM-MIMIC-MM from downloaded MIMIC-IV and MIMIC-CXR.ipynb`, I found that there is a function called `get_vision_embedding` in the last cell used to test the database, but I cannot find it in the GitHub repository. Could you please let me know what this function looks like, or if it exists under a different name?

Best,
Jun

**Comment by KoorinoMakoto** [comment]
> > This work was generated with the most recent MIMIC dataset we had availability to access at the time of publication. The exact version is all described in the paper (https://www.nature.com/articles/s41746-022-00689-4). It indeed may be the case that by the time you are trying to replicate this, the files may not match because the Physionet team does update their data versioning often. This is precisely why we added all the code we used to create the aggregated databases, etc. To allow for others to potentially use those to generate their own aggregated databases, embeddings and models. However, we will not directly support these adaptations as we do not currently have the bandwith to attend to this. We are actually working in much more scalable and future proofs to bring multimodality to clinical care.
> 
> Thank you for the reply. I have created the aggregated database using your detailed code. Appreciate you making all the code open-source.
> 
> However, in the notebook `1_Generate HAIM-MIMIC-MM from downloaded MIMIC-IV and MIMIC-CXR.ipynb`, I found that there is a function called `get_vision_embedding` in the last cell used to test the database, but I cannot find it in the GitHub repository. Could you please let me know what this function looks like, or if it exists under a different name?
> 
> Best, Jun

Hello, I also encountered the same problem in generating the dataset. I don't know how to solve it. You said you have successfully generated the dataset. Could you please share your code? Thank you very much.
