### ISSUE TITLE
Missing file

### ISSUE THREAD

**Issue by malika996** [lrsoenksen/HAIM#3]
To generate HAIM-MIMIC-MM data using **1_Generate HAIM-MIMIC-MM from downloaded MIMIC-IV and MIMIC-CXR.ipynb**, it seems that **mimic-cxr-2.0.0-jpeg-txt.csv** you're loading, `df_mimic-cxr_jpg =pd.read_csv(core_mimiciv_path + 'mimic-cxr-jpg/2.0.0/mimic-cxr-2.0.0-jpeg-txt.csv')`, to get image paths plus some extras, is actually missing in MIMIC-CXR-JPG v.2.0.0 database available at [physionet.org](https://physionet.org/content/mimic-cxr-jpg/2.0.0/)
<img width="600" alt="struct_mimic-cxr-jpg" src="https://user-images.githubusercontent.com/98698362/216788898-2d969682-aac1-44d5-8003-3308a15c9312.png">

How can I access this file?

**Comment by lrsoenksen** [comment]
You can download MIMIC CX2 V2.0.0 directly from Physionet (https://physionet.org/content/mimic-cxr/)

**Comment by lrsoenksen** [comment]
Thanks! The file has now been added to the following section of the git
https://github.com/lrsoenksen/HAIM/tree/main/mimic-cxr-jpg/2.0.0

Given upload limitations on github I had to split the file into two, but should be fine to decompress as one single file using 7-zip.

**Comment by xunmzii** [comment]
Hi~I have the same trouble in finding 'mimic-cxr-2.0.0-jpeg-txt.csv'. The link you gave on Feb 5 is not accessible now. How can I get access to the file now?

**Comment by lrsoenksen** [comment]
Hi All data related to MIMIC now needs to be obtained directly through Physionet. Official communication from Physionets states only they can provide credentialed access to any MIMIC data, so posting any of these files in Github is not allowed. Seems that the Physionet group has not yet officially released the notes, so it may be still a few months until you can access them via their website.

**Comment by xunmzii** [comment]
Okay, thanks for your timely response. Have a beautiful day~
