### ISSUE TITLE
Can't locate file

### ISSUE THREAD

**Issue by ArbelHaiman** [lrsoenksen/HAIM#9]
In your code, you refer to a file named: "mimic-cxr-2.0.0-jpeg-txt.csv", which seems to be a part of the files of the MIMIC-CXR-JPG dataset. However, I can't find this file anywhere in the data of Physionet...
Can you please refer to the location I can find this file?
Thank you

**Comment by lrsoenksen** [comment]
Hi @ArbelHaiman, indeed, those are the notes and text compiled from the images in CXR corresponding to MIMIC-IV. We wanted to add these here, but the policy from PhysioNet.org is that we cannot directly share this compiled data via github. Physionet is the only ones with permision to do si, I believe Physionet has either released these notes (through another file name) or is planning to do so as part of their full release of MIMIC-IV.

**Comment by ArbelHaiman** [comment]
I understand.
Thank you
